# Generated by Django 5.2 on 2025-05-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messenger', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hilo',
            options={'ordering': ['-fecha_modificacion']},
        ),
        migrations.AddField(
            model_name='hilo',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
